### ISSUE TITLE
Video embeds?

### ISSUE THREAD

**Issue by SLarrick** [sunlightpolicy/opendatapoliciesstatic#71]
Some of the policies were accompanied by a press conference or public hearing/reading that was publicly recorded (and is available on vimeo or youtube). @gregjd what do you think would be the best way to embed/include these videos on the site?

Here's an example of the policy video from cook county:
https://www.youtube.com/watch?v=3Vgi6AcecMU

**Comment by gregjd** [comment]
How common would you say this is?

**Comment by gregjd** [comment]
(@SLarrick)

**Comment by SLarrick** [comment]
Off the top of my head, new york city, baltimore, and seattle all did video for their open data policy signing (or for the subsequent press conference). Probably not that common though.

**Comment by gregjd** [comment]
Since we have a `notes` metadata field, for now I'd say we can put any video links in there if we really want to. Also we have a `press_url` metadata field for press releases, so any videos that are on the press-release pages will be captured there too.

If this is actually an important issue, we can add a dedicated metadata field, no problem.
